[build]
providers = ["php", "nodejs"]

[build.php]
version = "8.2"

[build.nodejs]
version = "20"

[build.php.build-commands]
run = ["composer install --no-dev --optimize-autoloader", "npm ci", "npm run build", "php artisan migrate:fresh --seed --force"]

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan event:cache && php artisan serve --host=0.0.0.0 --port=$PORT"

